"""

Revision ID: 18e4c67f96cb
Revises: 26ab60da29c5
Create Date: 2021-02-10 21:15:42.898854

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "18e4c67f96cb"
down_revision = "26ab60da29c5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "backtest_sessions", sa.Column("end_datetime", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "backtest_sessions", sa.Column("start_datetime", sa.DateTime(), nullable=True)
    )
    op.drop_column("backtest_sessions", "created_at")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "backtest_sessions",
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("backtest_sessions", "start_datetime")
    op.drop_column("backtest_sessions", "end_datetime")
    # ### end Alembic commands ###
