"""

Revision ID: 37056842ab4d
Revises: f8b14aae418d
Create Date: 2020-05-02 21:28:50.197746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "37056842ab4d"
down_revision = "f8b14aae418d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sources", sa.Column("config_json", sa.Unicode(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sources", "config_json")
    # ### end Alembic commands ###
