"""

Revision ID: 425ff5e5e715
Revises: 7a32a9c032b3
Create Date: 2021-02-28 21:13:37.484223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '425ff5e5e715'
down_revision = '7a32a9c032b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest_sessions', sa.Column('finished_datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtest_sessions', 'finished_datetime')
    # ### end Alembic commands ###
