"""

Revision ID: 47970e597206
Revises: 5bd7a5db869b
Create Date: 2021-03-05 00:30:36.868855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47970e597206'
down_revision = '5bd7a5db869b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sources_cache_session_id_fkey', 'sources', type_='foreignkey')
    op.drop_column('sources', 'cache_session_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('cache_session_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('sources_cache_session_id_fkey', 'sources', 'backtest_sessions', ['cache_session_id'], ['id'])
    # ### end Alembic commands ###
