"""

Revision ID: 68aea307b476
Revises: ae1979d9da38
Create Date: 2020-05-11 20:56:41.257086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "68aea307b476"
down_revision = "ae1979d9da38"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("strategies", sa.Column("is_live", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("strategies", "is_live")
    # ### end Alembic commands ###
