"""

Revision ID: 8aec74ca10a5
Revises: 18e4c67f96cb
Create Date: 2021-02-14 00:12:39.708565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8aec74ca10a5"
down_revision = "18e4c67f96cb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "backtest_sessions", sa.Column("backtest_type", sa.Unicode(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("backtest_sessions", "backtest_type")
    # ### end Alembic commands ###
