"""

Revision ID: a35cbd2ae378
Revises: 330a5e5e83a4
Create Date: 2020-07-09 20:33:52.459007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a35cbd2ae378"
down_revision = "330a5e5e83a4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Unicode(), nullable=True),
        sa.Column("is_always_on", sa.Boolean(), nullable=True),
        sa.Column("live_session_id", sa.Integer(), nullable=True),
        sa.Column("primary_live_source_id", sa.Integer(), nullable=True),
        sa.Column("secondary_live_source_id", sa.Integer(), nullable=True),
        sa.Column("primary_backtest_source_id", sa.Integer(), nullable=True),
        sa.Column("secondary_backtest_source_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["live_session_id"],
            ["live_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["primary_backtest_source_id"],
            ["sources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["primary_live_source_id"],
            ["sources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["secondary_backtest_source_id"],
            ["sources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["secondary_live_source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("resources")
    # ### end Alembic commands ###
