"""

Revision ID: ae1979d9da38
Revises: 37056842ab4d
Create Date: 2020-05-10 14:34:15.477047

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "ae1979d9da38"
down_revision = "37056842ab4d"
branch_labels = None
depends_on = None
strategy_typename = postgresql.ENUM(
    "interexchangearbitrage", "signalbased", name="strategytypesenum"
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # strategy_typename.create(op.get_bind())
    op.create_table(
        "strategies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Unicode(), nullable=True),
        sa.Column(
            "typename",
            sa.Enum(
                "interexchangearbitrage",
                "signalbased",
                name="strategytypesenum",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.Column("config_json", sa.Unicode(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("strategies")
    strategy_typename.drop(op.get_bind())
    # ### end Alembic commands ###
