"""

Revision ID: c1cf8d0f73e5
Revises: a32429525c6d
Create Date: 2020-07-14 22:14:28.625261

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c1cf8d0f73e5'
down_revision = 'a32429525c6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sources', 'typename',
            existing_type=postgresql.ENUM('bigquery', 'kuna', 'cryptowatch', name='sourcetypesenum'),
            type_=sa.Unicode(),
            nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sources', 'typename',
            existing_type=sa.Unicode(),
            type_=postgresql.ENUM('bigquery', 'kuna', 'cryptowatch', name='sourcetypesenum'),
            postgresql_using='typename::sourcetypesenum',
            nullable=True)
    # ### end Alembic commands ###
