"""

Revision ID: f5a91540a39d
Revises: 8aec74ca10a5
Create Date: 2021-02-21 00:15:19.161631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f5a91540a39d"
down_revision = "8aec74ca10a5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "backtest_sessions_sources",
        sa.Column("backtest_session_id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["backtest_session_id"],
            ["backtest_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("backtest_session_id", "source_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("backtest_sessions_sources")
    # ### end Alembic commands ###
