"""

Revision ID: f8b14aae418d
Revises: 20e592bb0fe7
Create Date: 2020-05-01 23:58:39.236722

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "f8b14aae418d"
down_revision = "20e592bb0fe7"
branch_labels = None
depends_on = None
typename = postgresql.ENUM("bigquery", "kuna", "cryptowatch", name="sourcetypesenum")


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    typename.create(op.get_bind())
    op.add_column("sources", sa.Column("name", sa.Unicode(), nullable=True))
    op.add_column(
        "sources",
        sa.Column(
            "typename",
            sa.Enum("bigquery", "kuna", "cryptowatch", name="sourcetypesenum"),
            nullable=True,
        ),
    )
    op.drop_column("sources", "type")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sources", sa.Column("type", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_column("sources", "typename")
    op.drop_column("sources", "name")
    typename.drop(op.get_bind())
    # ### end Alembic commands ###
