version: '3'
services:
  api:
    env_file:
      - ./api/.env
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        env: ${ENV}
        POETRY_VERSION: ${POETRY_VERSION}
    volumes:
      - ./api:/code
    # entrypoint: bash -c "scripts/migrate.sh && gunicorn --reload --bind 0.0.0.0:5000 --worker-class aiohttp.GunicornWebWorker --timeout 3600 --workers 1 --access-logfile - --capture-output test_migrations:app"
    # entrypoint: bash -c "scripts/migrate.sh && python test_migrations.py"
    entrypoint: bash -c "scripts/migrate.sh && adev runserver test_migrations.py"
    environment:
      - ENV=${ENV}
      - POETRY_VERSION=${POETRY_VERSION}
    ports: 
      - 5000:8000
      # - 5000:5000
      - 5678:5678
    links:
      - postgres
    depends_on:
      - postgres
    restart: on-failure
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
  # oldend:
  #   build:
  #     context: ./nextjs-react-hooks-example
  #     dockerfile: Dockerfile
  #     args:
  #       env: ${ENV}
  #   volumes:
  #     - ./nextjs-react-hooks-example:/code
  #   ports:
  #     - "3030:5000"
  #   restart: on-failure
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        env: ${ENV}
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
      - 9229:9229
    restart: on-failure
    # entrypoint: bash -c 'NODE_OPTIONS="--inspect=0.0.0.0:9229" node node_modules/next/dist/bin/next'
  pgadmin:
    image: dpage/pgadmin4
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: bausk@bausk.dev
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    logging:
      driver: none