release: scripts/migrate.sh
web: gunicorn --worker-class aiohttp.GunicornWebWorker --workers 1 --access-logfile - --capture-output test_migrations:app 
scheduler: gunicorn --bind 0.0.0.0:8001 --worker-class aiohttp.GunicornWebWorker --workers 1 --access-logfile - --capture-output scheduler:app